### ISSUE TITLE
Happy Fun Times: A similar yet nitch application

### ISSUE THREAD

**Issue by formula1** [Silk-GUI/Silk#15]
https://github.com/greggman/HappyFunTimes

This framework and ours are very similar

* Both have applications the user can install and remove (https://github.com/greggman/HappyFunTimes/blob/master/lib/games.js)
* applications can be run as they please (though he only allows one at a time)
* Both allow applications to be run on server and client
* both have a custom json aspect (his is [gameinfo.json](https://github.com/greggman/HappyFunTimes/blob/master/lib/gameinfo.js) ours is info.json)

Some things he did well

* [He launches a browser on startup](https://github.com/greggman/HappyFunTimes/blob/master/lib/browser.js) - We would have to do something similar except with fallbacks. first check if its NodeOS, if it is, we need to boot a chrome version that outputs directly to the framebuffer. next check if theres a boot to shell option. This would either be something like [atom-shell](https://github.com/atom/atom-shell/issues), [node-webkit](https://github.com/rogerwang/node-webkit) or something else. Then we would boot to browser. That being said, the only thing reliable and easy right now is the browser form.
* [Simple Method to look for a local server](http://happyfuntimes.net/) - All you have to do is go to that site and it finds a local server. [Here](https://gist.github.com/formula1/7f0fd8f1d11ec1bc092a) is his current version minified and a version I wrote that is much easier to read. It requires Async through bower though. This is useful when the app is a server of some kind that would be used and viewed over the local network.
* He has made the applications installable on windows http://superhappyfuntimes.net/install
* he takes advantage of the fact you can connect to the server. This is pretty awesome from the context of "the internet of things". This can be applied to lights in your house, tv remotes and anything that you can create a server with and want to control it with your phone. Obviously he chose to go down the path of games (Which I don't blame him because making games is freaking awesome.).

Some issues with his framework

* On clientside, you are forced to work within his environment. Its not terrible since its mostly AMD aspects and giving the developer generic objects to work with. But since we are more free, this is a downfall
* Almost everything is custom code/not abstract - Its a bit frustrating walking through his code. Some of which seems purposefully hidden.
* No webRTC - I was initially going to try and fix this, but his code is a bit frustrating to deal with
* no GamePad API support - This is not Silks issue, however it definitely opens up some important questions.

Some Differences

* he has a json file the individual games and allows the file to stay in the same directory. This can be both a good and bad thing (https://github.com/greggman/HappyFunTimes/blob/master/cli/cmds/add.js). Good because it allows the game to do whatever it pleases. Bad because it reduces automation.
* Some of the information is within the package.json which also may be more reliable since we can use npm rather than use 

PS: I'm still paying attention to this project. And Want to get back into it, but I also want to make sure we have a stun server that isn't google.

**Comment by zodern** [comment]
I am surprised how similar Happy Fun Times is to Silk.  It has a cool idea.

> Opening browser

When on platforms other than NodeOS, I have thought of using [open](https://www.npmjs.com/package/open).

> Installer

NodeOS users will probably know how to install an application from the command line.  I doubt there will be many people using Silk on Windows or Mac, but if there ever is an installer might be a good idea.

> This is pretty awesome from the context of "the internet of things". This can be applied to lights in your house, tv remotes and anything that you can create a server with and want to control it with your phone. 

That has a lot of potential.  Apps have enough freedom they could do this themselves.  Should Silk do anything to help apps with this?  I am going to make some changes to remote to work with apps that use a different port.  I also will add methods to the server api so apps can control remote.

**Comment by zodern** [comment]
> I'm still paying attention to this project. And Want to get back into it, but I also want to make sure we have a stun server that isn't google.

Great! I have learned a lot from you.

**Comment by formula1** [comment]
> open

That is an excellent library

> The installer 

I agree, its probably not necessary. But its food for thought to say the least

> Internet of things

I 100% agree with you that this should and can be done on an app level. To make it easier, there is [this script](https://gist.github.com/formula1/7f0fd8f1d11ec1bc092a) to find on wifi. Finding on bluetooth may be more complicated but still possible via (https://github.com/eelcocramer/node-bluetooth-serial-port) 

> Something related though completely seperate

I don't know if you know this or not but processes can send sockets and servers to eachother. This can be done (over child process)[http://nodejs.org/api/child_process.html#child_process_example_sending_server_object] and thanks to VanCoding [between completely unrelated processes](https://github.com/VanCoding/node-ancillary/). The second one I have no idea what to use it for but I think its really cool. It could be used as a load balancer or even a router where applications would connect to it rather than the application starts up the apps.

What this allows us to do is give all of our apps the sockets that are directed to them.

* We have access to the original request - https://github.com/einaros/ws/blob/master/doc/ws.md
* We read the request path via - `url.parse(ws.originalReq.url).path`
* We can check which app the websocket should be sent to `apps[path]`
* We send it to them `apps[path].fork.send("websocket", socket)`

This would be good for a few reasons

* We no longer need to relay messages from the applications fork to the server
* The server doesn't have to listen to sockets that aren't related to them within its loop

WebSockets are actually just tcp sockets, however `ws` creates a wrapper around it to make it easier to use. Unfortunately, we cannot send Objects, only sockets. I ran into a lot of frustration trying to make sure the websockets can be exported and imported, which in part relates to me being inactive temporarilly until I could get that togethor. We can also bypass ws in some ways by creating a tcp server that we then manually call [server.handleUpgrade](https://github.com/einaros/ws/blob/master/doc/ws.md#serverhandleupgraderequest-socket-upgradehead-callback) to construct the [ws.WebSocket](https://github.com/einaros/ws/blob/master/doc/ws.md#class-wswebsocket) within each child process. But that then requires every child process to require `ws` which may not be the best idea.

Trust me when I say I'm still actively thinking about Silk. Theres just a lot of code I've written that will never see the light of day : /. I just need a break from IO for a bit. I've been trying to translate code from one language to another, getting deep into other peoples code to see what I can do to scrap parts and learning new programming environments and its definitely tiring.

Thanks for letting me know you've learned from me. I'm certianly not @netlovers or @pirana but its cool I can share whatever tricks I can with you :)

**Comment by zodern** [comment]
I agree the web socket should be sent to the app.  Methods could remain in the app, and there could be public methods any app could call (such as app defaults).

In the dev branch I am trying [sockjs](https://github.com/sockjs/sockjs-node/). Web sockets didn't work with localtunnel and sockjs is able to emulate them.  The [connection instance](https://github.com/sockjs/sockjs-node/#connection-instance) it says supports Node Stream API, so I don't know if that means it is a stream or has a similar api.  It has a property for the url and pathname.

**Comment by formula1** [comment]
Here are possible issues

* ws.id doesn't exist - https://github.com/Silk-GUI/Silk/blob/dev/core/fork_framework/ws2fork_com.js#L82
* Your providing a url so that it can be cross domain but may not be implementing it on the browser (see sockjs_url) - https://github.com/sockjs/sockjs-node/#server-class
* You aren't hooking it into an actual http server - [example code](https://github.com/sockjs/sockjs-node/#server-instance)/[our code](https://github.com/Silk-GUI/Silk/blob/dev/server.js#L102) 

Wasn't a fan of my tunnel implementation? ;)

By the way, sockjs seems awesome. [this is its dependency](https://github.com/faye/faye-websocket-node). And that's [dependency](https://github.com/faye/websocket-driver-node) is even better!

[its api](https://github.com/faye/websocket-driver-node#driver-api) allows for the socket to still be a seperate aspect. This will allow the socket to be passed to child processes without (much) issue! There may be conflicts with handshaking, so it most likely cannot be created more than once. However, the request is an http request allowing us to see, parse and direct the request to the right location without creating it. Ah, give me some time and I'll get back into this. I'm getting all excited

**Comment by zodern** [comment]
Thank you for pointing those issues out.    I will try to fix them.

> Wasn't a fan of my tunnel implementation? ;)

I plan to use it.  I am not using it yet because it needs to be on a server.  Would it work on a free dynamo on Heroku?

**Comment by formula1** [comment]
It should work on heroku. Though It seems that with heroku you pay by hour unless I'm mistaken. That will most likely end up at about $30 a month. If your looking for free, sockjs probably has your back on that.

**Comment by zodern** [comment]
Heroku gives one dyno for free. https://www.heroku.com/pricing.

[Microsoft azure](azure.microsoft.com/en-us/pricing/calculator/) gives 10 websites and 5 gb bandwith for free.

I will keep localtunnel for now, but once Silk gets some users I will switch to your tunnel.  Something like remote.silk.io would be better than subdomain.localtunnel.me and the password protection in your tunnel will be nice.

**Comment by zodern** [comment]
In the dev branch, you can now open a nw.js window with the `--open flag`.  Added in 616a7df60b5b985d0edcefbe6c08a0ab239059b3

**Comment by formula1** [comment]
oooooo Thats sweet!
